version: "3.2"

services:
  python:
    image: python3
    build: ./python
    container_name: "PythonOnDocker"
    stdin_open: true
    tty: true
    working_dir: "/tmp/work"
    volumes:
      - ../python:/tmp/work
